name: 'Tests'

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    tests:
        name: 'Tests'
        strategy:
          matrix:
            php-versions: ['8.0', '8.1', '8.2', '8.3', '8.4']

        runs-on: 'ubuntu-latest'
        continue-on-error: ${{ !!matrix.experimental }}
        steps:
            - name: 'Check out repository'
              uses: 'actions/checkout@v4'

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php-versions }}

            - name: Compile extension
              run: |
                phpize
                ./configure
                make
            - name: Run tests
              run: |
                make test
